name: .NET
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    DOTNET_VERSION: "3.1.100"
    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: './DemoFunction'
      run: dotnet restore
    - name: Build
      working-directory: './DemoFunction'
      run: dotnet build --no-restore
    - name: Test
      working-directory: './DemoFunction'
      run: dotnet test --no-build --verbosity normal
    - name: Publish functions
      run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }}
    - name: Package functions
      uses: actions/upload-artifact@v1
      with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}
